### ISSUE TITLE
easyForm I18n Improvements

### ISSUE THREAD

**Issue by sandreas** [dockyard/ember-easy-form#105]
Hello,

first of all i would like to thank you for supporting I18n. Luckily i already use Ember.I18n, which is supported by default, but I would like to suggest 2 things, that would possibly improve the whole implementation.

1.) How about providing a Translation-Callback in Wrappers, so that easyForm does not depend on one single library, but can work with others (although the lib you chose is quite good in my opinion). 

2.) How about providing a setting in the wrapper, which element should be translated by default (e.g. label), without the need for a "...Translation"-Attribute? That would better fit the "write less"-Attitude of ember-Easyform, which i really like. And setting the value to false could disable translation completely to improve performance

Sample:

```
var emberWrapper = {
	formClass : 'form-horizontal',
	fieldErrorClass : 'error',
	errorClass : 'help-inline',
	hintClass : 'help-block',
	labelClass : 'col-sm-2 control-label',
	controlsWrapperClass : 'col-sm-8',
	inputTemplate : 'easyForm/myinput',
	labelTemplate : 'easyForm/mylabel',
	errorTemplate : 'easyForm/myerror',
	hintTemplate : 'easyForm/myhint',
        translateByDefault: 'label', // false disables translation to improve performance?
        i18nCallback: function(translationQualifier) {
              return myTranslate.t(translationQualifier);
       }
};

Ember.EasyForm.Config.registerWrapper('bs', emberWrapper);
```

```
// looks up for "firstname" as translationqualifier for label (translateByDefault)
// assuming that firstname would not be translated in two different ways
{{input firstname}}


// looks up for "special.firstname.translation" as translationqualifier for label
{{input firstname labelTranslation="special.firstname.tranlsation"}}
```

**Comment by diogomafra** [comment]
Most of the code of the library was rewritten to be compatible with Ember 1.13. Now you don't need to use the suffix `Translation` to define the translated text. You can use the helper of your library of choice.

For example, if you are using the addon [ember-i18n](https://github.com/jamesarosen/ember-i18n) you can do: 
```hbs
{{submit value=(t "pirate.submit")}}
```

So, answering your points:
1) You don't need to define any callback, just use the helper of the i18n library.
2) It's a good point. It's not supported right now but it would be very helpful.

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).
