### ISSUE TITLE
The formClass wrapper class is not applied when a form is represented by an Ember view

### ISSUE THREAD

**Issue by rbright** [dockyard/ember-easy-form#112]
I have a single page with multiple `form` elements backed by `Ember.View` objects. 
When loading a form, the `formClass` specified in my wrapper configuration is not applied - likely due to Ember applying the class name `ember-view`. All other elements within the form are wrapped correctly.

My view definitions look something like the following:

```coffeescript
App.SomeFormView = Ember.View.extend
  tagName: 'form'
  templateName: 'some_form'
  isVisible: Ember.computed.alias('controller.formVisible')

  submit: (e) ->
    e.preventDefault()
    @get('controller').send('update')
```

Its Emblem template:

```haml
#some-form-modal.modal.hide.fade
  .modal-header
    button.close type="button" data-dismiss="modal" aria-hidden="true" &times;
    h3 Some Form

  form-for model
    .modal-body
      = input name
        = label-field name
        = input-field name
        = error-field name

    .modal-footer
      button.btn.btn-primary type="submit" Save
      button.btn type="button" data-dismiss="modal" aria-hidden="true" Cancel
```

The `EasyForm` wrapper:

```coffeescript
Ember.EasyForm.Config.registerWrapper 'default',
  inputTemplate: 'bootstrap-input'
  controlsWrapperClass: 'controls'

  formClass: 'form-horizontal'
  labelClass: 'control-label'
  inputClass: 'control-group'
  fieldErrorClass: 'error'
  errorClass: 'help-inline'
  hintClass: 'help-block'
```

**Comment by diogomafra** [comment]
I  don't think this is a supported use-case. You can try to use the [wrapper-mixin](https://github.com/dockyard/ember-easy-form/blob/1-0-stable/addon/wrapper-mixin.js).

---

The library was updated to be an addon compatible with Ember 1.13 and 2.\*.

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).

Make sure to read the README and CHANGELOG on the `1-0-stable` branch.
