### ISSUE TITLE
form-for model in a needs controller

### ISSUE THREAD

**Issue by cerdiogenes** [dockyard/ember-easy-form#121]
I made a few changes to packages/ember-easyForm/lib/helpers/input-field.js so I could create forms for models inside a controller specified in needs. You can see my changes in https://github.com/cerdiogenes/ember-easyForm/commit/8708026cfc49c7e96677de886fbbede6be8b2194

I tried to create a test for it, but I'm stuck with an error. Could someone review it, please? https://gist.github.com/10423985

**Comment by diogomafra** [comment]
In previous versions, the context of the form was not very clear. In the most recent version it will always use the model passed to the `form-for` component.

----

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).

Make sure to read the README and CHANGELOG on the `1-0-stable` branch.
