### ISSUE TITLE
How to implement something similar to radio buttons in Ember EasyForm

### ISSUE THREAD

**Issue by digitalplaywright** [dockyard/ember-easy-form#123]
I have a form that creates a model with one attribute with two choices and another attribute with three choices, similarly to the way you select between private and public using radio buttons on https://github.com/new. I would like to implement this using something similar to radio buttons where all options are visible. However, radio buttons does not seem to be supported in Ember and Ember EasyForm.

Is there a recommended way to implement form input where all options are visible and only one can be selected?

**Comment by diogomafra** [comment]
There are a few addons that provide radio button components: http://www.emberaddons.com/?query=radio

You can create a custom input type using one of those components: https://github.com/dockyard/ember-easy-form#custom-input-types
