### ISSUE TITLE
Documentation of expected interfaces in controller and model

### ISSUE THREAD

**Issue by digitalplaywright** [DockYard/ember-easy-form#125]
I am trying Ember EasyForm as a convenience over vanilla forms, but my submit action is silently failing and I suspect it is because there is something I should be doing in the controller and view that I am not doing.  

Are there any examples or guides I could look at showing the model, controller and template for a form submission? I can not find any documentation or examples of this.

**Comment by bcardarella** [comment]
Closing in favor of #229
