### ISSUE TITLE
Nested/embedded object forms / validation error handling

### ISSUE THREAD

**Issue by ahacking** [DockYard/ember-easy-form#126]
I am using the ember-validations library with ember-easyForm and they both work very well together for simple model objects.  However with nested/embedded objects the error handling in easyForm is unable to bind to errors on nested model objects.

Part of the problem area appears to be here:
https://github.com/dockyard/ember-easyForm/blob/master/packages/ember-easyForm/lib/views/error.js#L6

```
Ember.Binding.from('formForModel.errors.' + this.property).to('errors').connect(this);
```

I am thinking there may need to be a bit more flexibility in how easyForm binds to model errors generally.

For the specific case of using ember-easyForm with nested models that have ember-validations defined on them, the binding would be determined as follows:

```
var propPath = this.property.split('.');
propPath.unshift('formForModel');
propPath.insertAt(-1,'errors');
Ember.Binding.from(propPath.join('.')).to('errors').connect(this);
```

The above snippet handles both non-nested and nested property paths where validation errors hang off each model object. eg a simple use case of a Person model containing a nested Address model with validations defined on each of the model classes.

More deeply however, how would one handle a form containing a collection of nested items? AFAIKT array indexes can't be specified in property paths and HTML forms can't be nested, but easyFrom views _should_ be able to nest and support using {{#each}} over nested collections, similar to the way various rails form builder approaches allow one to use "fields-for' on nested models to set the nested form/object context.  A simple use case being a Person having multiple Addresses, and presenting a form that contains the person input fields and the nested address input fields in some "designer-knows-best" aka "arbitrary" order on a single form.

 Open to suggestions on an acceptable way forward so I can work up a PR.

**Comment by bcardarella** [comment]
Closing in favor of #229
