### ISSUE TITLE
Improve form-for documentation (model vs controller)

### ISSUE THREAD

**Issue by mgraham** [dockyard/ember-easy-form#128]
What is the difference between calling {{form-for model}} and {{form-for controller}}?
Some examples use model and some use controller.  I have found that validations don't work properly when you use model.  Is there any reason to use model over controller?

**Comment by diogomafra** [comment]
In previous versions, the context of the form was not very clear. In the most recent version it will always use the model passed to the `form-for` component.

----

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).

Make sure to read the README and CHANGELOG on the `1-0-stable` branch.
