### ISSUE TITLE
Simple example for easyForm with ember-validations

### ISSUE THREAD

**Issue by BenjaminHorn** [DockYard/ember-easy-form#134]
Hi Brian!

I saw your demonstration video: https://www.youtube.com/watch?v=ZWUjlbN8fvA and i try to recreate it on JsBin: http://emberjs.jsbin.com/koyojazi/12/edit

~~Unfortuneatly i cant see any error.~~

EDIT: Finally i got it to work:
-validations must go into the controller (?)
-insted of  {{#form-for model}} i used {{#form-for controller}}

thats solved the problem, but as i read model should work too. I dont understan why isnt...

How can i change the value of submit. I have tried:
{{ submit value="somethingelsethensubmit"}}

 Any help would be great. TY

**Comment by SpOOnman** [comment]
Last commit on example application is from Jul 24, 2014. It contains some hacks and todos inline (e.g. app.coffee). How does it compare to current version?

I am new to Ember and I cannot find any good source of how to install this addon and setup your project.

**Comment by timmyomahony** [comment]
This is still an issue. It's not clear how to use the two libraries together. Furthermore, trying to pass the controller (with `1.0.0-rc-1`) causes the following error:

> Assertion Failed: Using `{{controller}}` or any path based on it ('/path/to/my/app/template.hbs' @ L5:C0) has been removed in Ember 2.0

**Comment by bcardarella** [comment]
Closing in favor of #229
