### ISSUE TITLE
How to set selected in selectbox

### ISSUE THREAD

**Issue by BenjaminHorn** [dockyard/ember-easy-form#136]
I followed the documentation:
```Javascript
{{#form-for model}}
  {{input firstName}}
  {{input lastName}}
  {{input bio as="text"}}
  {{input country as='select'
       collection="App.countries"
       selection="country"
       optionValuePath="content.id"
       optionLabelPath="content.name"
       prompt="Select Country"
  }}
{{/form-for}}
```

but i cant select an option.
Here is the JsBin: http://emberjs.jsbin.com/EveQOke/59/edit

**Comment by diogomafra** [comment]
Most of the code of the library was rewritten to be an Ember addon compatible with Ember 1.13.

The select view was deprecated on Ember 1.13 and removed on Ember 2.0. To support both versions we had to remove the direct support for it. You can define a custom input helper using any select component you want.

Here is a gist showing how to write a custom input type for the `select` component: https://gist.github.com/diogomafra/9c2b3e2fc1f3dcff59f0

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).
