### ISSUE TITLE
Is the submit button text translateable?

### ISSUE THREAD

**Issue by changwuf31** [dockyard/ember-easy-form#137]
I've searched the documentation, but non exists.

**Comment by diogomafra** [comment]
Yes, in the most recent version you can translate it.

```hbs
{{submit value=(t "your-translation-key")}}
```

-----

The library was updated to be compatible with Ember 1.13 and 2.\*.

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).

Make sure to read the README and CHANGELOG on the `1-0-stable` branch.
