### ISSUE TITLE
Ability to remove default classes

### ISSUE THREAD

**Issue by Emerson** [DockYard/ember-easy-form#139]
Great library!

I have one small issue that is probably an edge case, but is certainly a valid one.

In my app, I have a `Label` field. easyForm generates many of the elements related to this field with a `.label` class. This causes issues in Bootstrap, as anything with the label class appears as a formal bootstrap label.

Is there anyway to remove/override this default class? I've tried reopening the BaseView, but that does not seem to work.

Any help would be much appreciated.

**Comment by bcardarella** [comment]
Closing in favor of #229
