### ISSUE TITLE
Same functionality for select as for input.

### ISSUE THREAD

**Issue by Retistic** [dockyard/ember-easy-form#142]
Perhaps Ember.EasyForm.BaseView should be turned into a mixin so that instead of extending just Ember.View, it can be applied to Ember.Select as well, This will enable adding classes and overriding templates for form selects.

**Comment by diogomafra** [comment]
The most recent version of the library has a mixin for that: https://github.com/dockyard/ember-easy-form/blob/1-0-stable/addon/wrapper-mixin.js
