### ISSUE TITLE
input as='select' does not select first option by default

### ISSUE THREAD

**Issue by andrewfan** [dockyard/ember-easy-form#151]
https://github.com/emberjs/ember.js/blob/v1.6.1/packages_es6/ember-handlebars/tests/controls/select_test.js#L138

**Comment by diogomafra** [comment]
Most of the code of the library was rewritten to be an Ember addon compatible with Ember 1.13.

The select view was deprecated on Ember 1.13 and removed on Ember 2.0. To support both versions we had to remove the direct support for it. You can define a custom input helper using any select component you want.

Here is a gist showing how to write a custom input type for the `select` component: https://gist.github.com/diogomafra/9c2b3e2fc1f3dcff59f0

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).
