### ISSUE TITLE
Validations not displaying, property not syncing

### ISSUE THREAD

**Issue by Kikketer** [dockyard/ember-easy-form#155]
I think with an issue this large, I have to be missing something.  I'm using Ember-CLI .40 and have brought the libraries in via modifying my Brocfile.js:

```
app.import('vendor/ember-validations/ember-validations.js');
app.import('vendor/ember-easyform/ember-easyform.js');
```

I have a test of non-easy form and with easy form.  The non-easy form seems to work (sorta), but the easy form version just fails on all fronts.  Here's my index.hbs:

```
<form {{action login on='submit'}}>
  {{input value=username placeholder='username'}}
    <button>Yay</button>
    <div class="error">{{errors.username}}</div>
</form>

<br />

{{#form-for model}}
  {{#input username}}
    {{input-field username}}{{label-field username}}
    <br/>
    {{error-field username}}
  {{/input}}
  {{submit}}
{{/form-for}}
```

The non-easy is sitting at the top, the error message always displays even on load.

The bottom half is the easy version.  The "username" property does not sync with anything else, so when I throw characters into that input nothing else reflects changes.  I found if I use `value=username`, it does sync properly.

No matter what however, the `{{error-field username}}` has never shown for me yet in any of my tests.  The controller looks like this:

```
import Ember from 'ember';

export default Ember.Controller.extend(Ember.Validations.Mixin, {

  actions: {
    login: function() {
      console.log('Submit?');
      return false;
    }
  },

  validations: {
    username: {
      presence: true
    }
  }
});
```

Should this error field show when I blur?  I noticed the submit button is disabled, but ALWAYS disabled.

**Comment by diogomafra** [comment]
In previous versions, the context of the form was not very clear. In the most recent version it will always use the model passed to the `form-for` component.

----

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).

Make sure to read the README and CHANGELOG on the `1-0-stable` branch.
