### ISSUE TITLE
No way to pass content to input as="select"

### ISSUE THREAD

**Issue by rynam0** [dockyard/ember-easy-form#163]
I'm experiencing an issue where I need to pass a "content" attribute to the {{input myprop as="select"}} helper.  I'm noticing that the "collection" attribute is a contentBinding property and automatically appends the model to the binding path.  I'm able to get Ember.Select to use the content attribute but have no way to do this via Ember EasyForm.  As this is a "wrapper" to Ember.Select, why the lack of support of the direct "content" attribute.  Are there any workarounds you can think of to get me by in the meantime?

Thanks!

Example: 
{{view Ember.Select content=view.content.allowedValues  optionLabelPath="content.name" optionValuePath="content.id" prompt="..." selection=newTicket.priority}}

I would need some way to do the same as the following does not work for me:
{{input priority as="select" content=view.content.allowedValues prompt="..." optionValuePath="content.id" optionLabelPath="content.name"}}

**Comment by rynam0** [comment]
Thanks, @ZenCocoon.  Being a n00b i missed that.

**Comment by diogomafra** [comment]
This is related to the PR #164
