### ISSUE TITLE
Convert to Ember CLI Addon

### ISSUE THREAD

**Issue by Panman8201** [dockyard/ember-easy-form#165]
I'm sure this is already in the plans but just wanted to start an Issue to keep track. Thanks for this BTW!

**Comment by leejt489** [comment]
@bcardarella @kristianmandrup What is the plan for easier installation?  Might this be available as a node module on npm?

Thanks!

**Comment by tibotiber** [comment]
+1

**Comment by willviles** [comment]
+1

**Comment by lucasloami** [comment]
+1

**Comment by kristianmandrup** [comment]
I did an initial port as a cli plugin last year. Not on ember at this time. Someone else please take over ;)

**Comment by Kae2312** [comment]
+1 would be very useful!

**Comment by kristianmandrup** [comment]
Try to work from this...

https://github.com/kristianmandrup/ember-easyform-cli

**Comment by diogomafra** [comment]
The library was updated to be an addon compatible with Ember 1.13 and 2.\*. :smiley:

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).

Make sure to read the README and CHANGELOG on the `1-0-stable` branch.
