### ISSUE TITLE
Uncaught Error: Assertion Failed: You specified the templateName formfieldinput for <Ember.EasyForm.Input:ember474>, but it did not exist. 

### ISSUE THREAD

**Issue by emorling** [dockyard/ember-easy-form#168]
I am trying the Bootstrap 3 and Ember Data With Server Side Validations as outline here:
https://github.com/dockyard/ember-easyForm/wiki/Bootstrap-3-and-Ember-Data-With-Server-Side-Validations

However this causes this error
Uncaught Error: Assertion Failed: You specified the templateName form-fields/input for <Ember.EasyForm.Input:ember474>, but it did not exist. 

Any ideas?

**Comment by diogomafra** [comment]
I think @seriousben's answer solves your problem. I'm closing this issue.
