### ISSUE TITLE
Passing options to custom input

### ISSUE THREAD

**Issue by yratanov** [dockyard/ember-easy-form#170]
Hello, 

I have the following code:
```coffee
App.SliderField = Ember.TextField.extend
  min: null
  max: null
  didInsertElement: ->
    @$().slider(min: @get('min'), max: @get('max'), value: @get('value'))

  updateValue: (->
    @$().slider('setValue', @get('value'))
  ).observes('value')


Ember.EasyForm.Config.registerInputType('slider', App.SliderField)
```

Template:
```handlebars
{{input numberOfSomething as="slider" min=100 max=1000}}
```

But ```min``` and ```max``` is null in ```App.SliderField ``` instance...
I have tried to pass them as ```inputConfig="min:100;max:1000"```, but no luck...

Is there any way to pass settings to my custom input?

PS: If I add ```min```and ```max``` to the ```Ember.EasyForm.Input.inputOptions``` everything works, but I don't think it is a good solution.

**Comment by andrewfan** [comment]
@yratanov, @sbounmy, @jcope2013 you can proxy those fields from parentView in your case: 

    max: Ember.computed.alias('parentView.max'),
    min: Ember.computed.alias('parentView.min'),
   
and then pass max in `input` helper
   
    {{input numberOfSomething as="slider" min=100 max=1000}}

**Comment by diogomafra** [comment]
Most of the code of the library was rewritten to be an Ember addon compatible with Ember 1.13 and 2.\*.

Now it's possible to do exactly what you want. Any option passed to the `input-for` component is passed to you custom input.

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).

Make sure to read the README and CHANGELOG in the `1-0-stable` branch.
