### ISSUE TITLE
Make it possible to replace the backing model

### ISSUE THREAD

**Issue by jacobk** [dockyard/ember-easy-form#172]
I needed to use easyForm in a scenario where the underlying model was replaced by another model after successful submission.

I'm not sure this scenario is something that you want to support, but my current solution looks something like this if you are interested:

```javascript
  Ember.EasyForm.BaseView.reopen({
    init: function() {
      this._super();
      var formForModelPath = this.get('templateData.keywords.formForModelPath'),
          contexts = ['context', 'controller', 'this'],
          path = 'context';
      if (!contexts.contains(formForModelPath)) {
        path = 'context.' + formForModelPath;
      }
      Ember.defineProperty(this, 'formForModel', Ember.computed.alias(path));
    }
  });
```

This is not thoroughly tested and may cause other issues I haven't thought about. I'm afraid I don't have time for a proper PR atm but I wanted to mention this here for others that might have the same needs and for your consideration.

**Comment by diogomafra** [comment]
I think this is already supported in the most recent version.

----

The library was updated to be an addon compatible with Ember 1.13 and 2.\*.

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).

Make sure to read the README and CHANGELOG on the `1-0-stable` branch.

**Comment by jaredcnance** [comment]
I think this is still an issue. I'm experiencing a similar issue when transitioning to the same route, with a different model.

Transition is done either by:
`this.transitionTo('same-route', newModel);`
or by
`{{link-to "same-route" newModel.id}}`

I can verify the model is changing in the `afterModel` hook as well as in the template.

The current package I am using is:
`"ember-easy-form": "https://github.com/dockyard/ember-easy-form.git#1-0-stable",`

Example form:
```
{{#form-for model}}
  {{input-for "name" label="Name" required="true"}}
  <button class="ui right floated positive button" {{action (action "save")}}>
    Save
  </button>
{{/form-for}}
```
