### ISSUE TITLE
"Uncaught Error: Unknown template object: function" when using easyForm with ember-cli-htmlbars and handlebars 2.0

### ISSUE THREAD

**Issue by jcope2013** [dockyard/ember-easy-form#175]
when using this package with handlebars 2.0 and ember-cli-htmlbars (http://emberjs.com/blog/2014/10/16/handlebars-update.html)

I get this error in my app
 
     "Uncaught Error: Unknown template object: function" 
   
seems to be related to this line

    bower_components/ember-easyForm/index.js:540 - (anonymous function) 

    template: Ember.Handlebars.template(function anonymous(Handlebars,depth0,helpers,partials,data) 

stacktrace

  ```Uncaught Error: Unknown template object: function vendor.js:10882template          vendor.js:10882hb.template vendor.js:11071(anonymous function) bower_components/ember-easyForm/index.js:540(anonymous function) bower_components/ember-easyForm/index.js:562requireModule vendor.js:77reify vendor.js:48requireModule vendor.js:76(anonymous function) vendor.js:64190default vendor.js:64189(anonymous function) inbox-  dashboard/app.js:22requireModule vendor.js:77(anonymous function)```

**Comment by jwahdatehagh** [comment]
@rwjblue 
Your #176 fix works for me, thanks!

**Comment by blimmer** [comment]
Thanks for the update @jwahdatehagh , @bcardarella is it possible to publish a master build to http://builds.dockyard.com/ ?

**Comment by jcope2013** [comment]
@jwahdatehagh what version of ember are you running against?

**Comment by jwahdatehagh** [comment]
sorry - i'm running 1.9.1 ...

This is my ember-cli initializer (i built EasyForms and copied it over..)
https://gist.github.com/jwahdatehagh/f06fab8037965f788b0c

Good luck!

**Comment by sir-dunxalot** [comment]
Any update on this since Ember 1.10 had now landed? Thanks.

**Comment by sir-dunxalot** [comment]
If you want to get Easy Form running with Handlebars 2.0 and Ember 1.10 we wrote [an addon that works with the latest Ember CLI dependencies](https://github.com/sir-dunxalot/ember-easy-form-extensions). You can install that but note it enhances the basic Easy Form functionalities so you might want to check out the source ([specifically this file](https://github.com/sir-dunxalot/ember-easy-form-extensions/blob/master/vendor/ember-easy-form.js) and [this file](https://github.com/sir-dunxalot/ember-easy-form-extensions/blob/master/addon/initializers/easy-form-extensions.js)) to see how it's been implemented. Hopefully that will help a few people!

**Comment by jcope2013** [comment]
@sir-dunxalot thanks, i am still getting the same error though as mentioned here (https://github.com/dockyard/ember-easy-form/issues/175#issuecomment-65967796) on line 138 https://github.com/sir-dunxalot/ember-easy-form-extensions/blob/master/vendor/ember-easy-form.js#L138

**Comment by sir-dunxalot** [comment]
@jcope2013 Fixed! If you have anymore issues with that addon you can open an issue on the [addon's repo](https://github.com/sir-dunxalot/ember-easy-form-extensions) but the code you'll need to reference to make Easyform compatible with HTMLBars [is here](https://github.com/sir-dunxalot/ember-easy-form-extensions/blob/master/vendor/ember-easy-form.js) - it's a hack job but it'll put you on the right path!

**Comment by blimmer** [comment]
We got ember-easy-forms working with 1.11.3 and @sir-dunxalot 's shim, however testing against the newly implemented Glimmer engine on canary, the shim is broken. I sure hope that scoped helpers get merged soon so work can begin on easyform 2.0. We're laying on hack after hack to keep up-to-date with Ember while keeping easy forms working. It's also the source of hundreds of deprecations in our inspector due to the use of `*Binding` properties.

@rwjblue is there anything we can do to help get the [scoped helpers](https://github.com/emberjs/ember.js/pull/10244) PR through the process? IIRC that was the last true blocker to begin work on easy-form 2.0. Last I saw we were waiting on glimmer to get flushed out a bit more before that PR could move through the process.

**Comment by diogomafra** [comment]
The library has been updated to be an addon compatible with Ember 1.13 and 2.\*.

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).

Make sure to read the README and CHANGELOG on the `1-0-stable` branch.
