### ISSUE TITLE
span.error is not rendered

### ISSUE THREAD

**Issue by jackmatt2** [DockYard/ember-easy-form#191]
```
    "ember-easyForm": "http://builds.dockyard.com.s3.amazonaws.com/ember-easyForm/latest/ember-easyForm.prod.js"
```

When my controls are rendered I can't see any `span.error` tags in the DOM, therefore, no error messages are being displayed.

I have a "controls" array in the controller.  This contains each field in controller.model with the the tup of control to use isText, isSelect etc.  I then iterate the controls and output the form elements.

```
            {{#if control.isText}}
                {{input control.field label=control.label disabled=control.disabled name=control.name}}
            {{/if}}
```

output

```
<div class="ember-view string control.field form-group" id="ember1017">
<label for="ember1022" class="ember-view control.field control-label" id="ember1021">Name</label><input name="name" class="ember-view ember-text-field" id="ember1022" type="text">
</div>
```

Why is the span.error tag not being displayed?

**Comment by bcardarella** [comment]
Closing in favor of #229
