### ISSUE TITLE
Support ember-cli-i18n

### ISSUE THREAD

**Issue by angusfretwell** [dockyard/ember-easy-form#192]
Would be great if this could support ember-cli-i18n as it does ember-i18n. I suppose it would make sense to drop ember-i18n support once this is converted to a CLI add-on?

**Comment by diogomafra** [comment]
Most of the code of the library was rewritten to be an ember addon, compatible with Ember 1.13 and 2.\*. 

The support for internationalization was removed, but you can use the i18n helper of your library of choice, as you are showing in your example. I think you don't need to use `unbound` anymore, but I din't test it.

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).
