### ISSUE TITLE
Explict type="text"

### ISSUE THREAD

**Issue by carlbennettnz** [DockYard/ember-easy-form#194]
I want to bind the `color` key on my model to a normal text input, not a color picker. As far as I can tell, this isn't possible with the `as` option. Is there a workaround?

``` handlebars
{{! This should be a text input. }}
{{input color label="Color"}}
```

**Comment by sir-dunxalot** [comment]
`type='none` is a workaround. I've used that many times in the past.

**Comment by bcardarella** [comment]
Closing in favor of #229
