### ISSUE TITLE
Ember CLI Addon / Bower

### ISSUE THREAD

**Issue by gf3** [dockyard/ember-easy-form#195]
Hey, any plans to `ember-cli-addon`-ify this package and add it to bower? It'd greatly simplify the process of getting, installing, and using this project. Especially since it looks like `ember-cli` is going to be the defacto ember tool.

**Comment by bcardarella** [comment]
Yes, I am dedicating February to OSS where this will happen. Apologies for the delay :(

**Comment by gf3** [comment]
No worries at all, was just curious. Thanks!
