### ISSUE TITLE
Readme points to builds.dockyard.com, yet the S3 hasn't been updated since july

### ISSUE THREAD

**Issue by igorT** [dockyard/ember-easy-form#198]
I might just be looking at the wrong place?

**Comment by strukturedkaos** [comment]
@igorT - were you able to figure this out?

**Comment by jcope2013** [comment]
latest build here 

https://gist.github.com/jwahdatehagh/f06fab8037965f788b0c

**Comment by diogomafra** [comment]
The library was updated to be an addon compatible with Ember 1.13 and 2.\*.

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).

Make sure to read the README and CHANGELOG on the `1-0-stable` branch.
