### ISSUE TITLE
Information on adding this to a fresh ember.js project?  Can't find it in Readme.

### ISSUE THREAD

**Issue by joshuairl** [dockyard/ember-easy-form#199]
I'm new to ember.js and i want to use this addon but no matter what I do it's not available in npm, bower, etc.  How does one add this to their existing ember.js project?

**Comment by leejt489** [comment]
@joshuairl I believe you either get a pre-built library https://github.com/dockyard/ember-easy-form#getting-a-build or you build yourself https://github.com/dockyard/ember-easy-form#building-yourself

I think there is some plan to make this available as an ember-cli addon or something, but not sure exactly. #165

**Comment by diogomafra** [comment]
The library was updated to be an addon compatible with Ember 1.13 and 2.\*.

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).

Make sure to read the README and CHANGELOG on the `1-0-stable` branch.
