### ISSUE TITLE
undefined is not a function (evaluating 'Ember.Handlebars.helpers['ember-input'].call(this, arguments[0])')

### ISSUE THREAD

**Issue by Azdaroth** [dockyard/ember-easy-form#201]
Hi, after updating to ember-cli 0.2.3 I'm getting `[Error] TypeError: undefined is not a function (evaluating 'Ember.Handlebars.helpers['ember-input'].call(this, arguments[0])')`, didn't have problems with ember-cli 0.1.x version. Any idea what's the problem about?

**Comment by angusfretwell** [comment]
I'm having the same issue.

@Azdaroth, were you able to find any workarounds?

**Comment by Azdaroth** [comment]
@angusfretwell Pretty ugly solution, but I just commented out the code. Unfortunately, it turned out that there were more things that didn't work so stopped using ember-easy-form for now ;/.

**Comment by angusfretwell** [comment]
Thought that might be the case, bit of a shame. :(

**Comment by msquitieri** [comment]
Any update on this? Having the same issue on non-ember cli project with Ember version 1.11.3.

**Comment by GCorbel** [comment]
I have the same bug here

**Comment by diogomafra** [comment]
The library was updated to be compatible with Ember 1.13 and 2.\*.

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).

Make sure to read the README and CHANGELOG on the `1-0-stable` branch.
