### ISSUE TITLE
How Do I Stop Generation of <label> and <div> elements?

### ISSUE THREAD

**Issue by grayskwrl149** [dockyard/ember-easy-form#203]
This line in my template
```hbs
{{input searchTerm action="search" placeholder="Search..." id="searchThing"}}
```
creates a ```<label>``` and a ```<div>```, and then creates the ```<input>``` inside the ```<div>```.
```html
<label id="ember1311" class="ember-view control-label">Search term</label>
<div>
   <input id="searchThing" class="ember-view form-control ember-text-field" placeholder="Search..." type="text">
</div>
```

I don't want the ```<label>``` or the ```<div>``` elements, just the ```<input>```. How do I stop them from being generated?

**Comment by diogomafra** [comment]
You can register a "wrapper" with a custom template in for the label and input. Please check this section of the README: https://github.com/dockyard/ember-easy-form/tree/1-0-stable#wrappers

---

The library was updated to be compatible with Ember 1.13 and 2.\*.

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).

Make sure to read the README and CHANGELOG on the `1-0-stable` branch.
