### ISSUE TITLE
How to get view inside form-for?

### ISSUE THREAD

**Issue by vvscode** [dockyard/ember-easy-form#204]
I'm trying to get access to view's property from template but got an undefined. 

After logging view from template I've got:

```
  {{log view}}
  {{#form-for form  wrapper="modal" class="[FORM_CLASS]"}}
  {{log view}}
```

```
Class {_outlets: Object, elementId: "ember3726", currentState: Object, _state: "inBuffer", _isVisible: true…}

Class {helperName: "view", classNames: Array[2], class: "[FORM_CLASS]", templateData: Object, _context: Class…}
```

First one is "ember3726" and last one is "ember3751" ( last isn't an instance of my View class )

My temporary solution is wrap all form with
```
{{#with view as modalView}}
```
but I want to know is it correct way and what is happening?

**Comment by markhorgan** [comment]
Inside form-for, view refers to the Ember.EasyForm.Form view. To access YOUR view you could write view.parentView.

**Comment by diogomafra** [comment]
I think @markhorgan's answer is correct. I'm closing this issue.
