### ISSUE TITLE
What's the road map?

### ISSUE THREAD

**Issue by xomaczar** [dockyard/ember-easy-form#205]
I bet on this addon about a year and a half ago, mainly because this addon was developed and 'maintained' by the dockyard - the premier ember shop. Now with every new ember release I've spend enormous amount of time trying to hack a working solution. With the latest release of ember 1.13, the not so easy-form-hackathon stops for me. I know there were plans to re-write this library way back when, are they still on the table or ...

**Comment by bcardarella** [comment]
https://github.com/dockyard/ember-easy-form/issues/196

**Comment by bcardarella** [comment]
I feel your pain. I am currently blocked by the scoped helpers feature not landing in Ember 2.x. This is also difficult for our client apps, but the reality if open source is time and commitment. I can't sink time into supporting a library that is currently hand-cuffed upstream by Ember itself. If easy-form is blocking you from upgrading we're happy to work with your employer in the form of sponsoring an OSS effort to get it there. If not, then we'll all have to wait for scoped helpers.
