### ISSUE TITLE
Password as="text"

### ISSUE THREAD

**Issue by kairel** [dockyard/ember-easy-form#207]
Hi , 

Her my code:

          {{#input password}}
            {{label-field password textTranslation="attributes.password" class="col-sm-5 control-label"}}
            <div class="col-sm-5">
              {{input-field password class="form-control"}}
              {{#if view.showError}}{{error-field password}}{{/if}}
            </div>
          {{/input}

But the password is hide (******). How i force to display the password as a text (not textarea just input)?

Regards

**Comment by bcardarella** [comment]
I think you can get around this by doing:

```js
{{#input password}}
  {{input-field password class="form-control" as=""}}
{{/input}}
```

**Comment by bcardarella** [comment]
Actually, empty string eval as `false` in JS. You can probably use a bogus input type: `as="string"`

**Comment by kairel** [comment]
Thanks @bcardarella , it work with this bogus
