### ISSUE TITLE
How does the input component generate the label with the attribute?

### ISSUE THREAD

**Issue by glenlivet** [dockyard/ember-easy-form#211]
For instance, `{{input firstName}}` will generate a label `<label>First name</label>` along with the input tag.

I'm very interesting how the label is generated. I know it is somehow get the attribute `firstName` attr name. I don't know how to get it. 

I tried to dig into the code, but I'm still new to emberjs and is not able to get a clue from code. Can anyone explain it a bit? 

Thanks.

**Comment by diogomafra** [comment]
You can see the most recent version on the `1-0-stable` branch. Now it's an ember addon, it's easier to understand what's going on.

Here is the label-field component: https://github.com/dockyard/ember-easy-form/blob/1-0-stable/addon/components/label-field.js
