### ISSUE TITLE
 TypeError: options.data.view.getStream is not a function

### ISSUE THREAD

**Issue by vvscode** [dockyard/ember-easy-form#213]
Trying use 
``    "ember-easy-form": "dockyard/ember-easy-form#1-0-stable",``` for ember-1.13 based app
and got 

```
Uncaught TypeError: options.data.view.getStream is not a functionhandlebarsGet @ input-field.js:20exports.default @ input-field.js:33helperFunc @ ember.debug.js:6710_emberMetalMerge.default.compute @ ember.debug.js:11273Stream.value @ ember.debug.js:22137invokeHelper @ ember.debug.js:8483inline @ ember.debug.js:52174_htmlbarsUtilObjectUtils.merge.inline @ ```

Is there any solution?

Thx

**Comment by diogomafra** [comment]
The branch `1-0-stable` is not compatible with Ember 1.13 yet. I'm working on a PR that makes it compatible with 1.13 and 2.\*. Please, see this PR: https://github.com/dockyard/ember-easy-form/pull/212

Maybe you can test my branch in your project. Just make sure to read the CHANGELOG and README.

**Comment by vvscode** [comment]
@diogomafra  thx, I'll try in few days.
