### ISSUE TITLE
No license file in top-level directory

### ISSUE THREAD

**Issue by ralmidani** [dockyard/ember-easy-form#214]
I am interested in this project, and plan to use it once it is updated for Ember's 2.x line.

The license file is currently in the "generators" directory. I had to go looking for it. It would be better if people who need a license could find it right away, lest they be discouraged.

**Comment by diogomafra** [comment]
Hi @ralmidani, the license info is in the end of the README (in the [Legal](https://github.com/dockyard/ember-easy-form#legal) section).

The most recent version of the library is on the branch `1-0-stable`. It is compatible with Ember 1.13 and 2.\*. In that branch there is a LICENSE.md file. :smile: 

You can get the most recent version of ember-easy-form on the branch `1-0-stable` or as an ember-addon [here](https://www.npmjs.com/package/ember-easy-form).
