### ISSUE TITLE
Getting Uncaught TypeError: Ember.Handlebars.registerHelper is not a function

### ISSUE THREAD

**Issue by meliborn** [DockYard/ember-easy-form#216]
Ember 2.2.0
Seems it's because new API.

**Comment by bcardarella** [comment]
While version are you using?

**Comment by meliborn** [comment]
@bcardarella Ember? 2.2.0

**Comment by bcardarella** [comment]
no, for easy-form

**Comment by meliborn** [comment]
latest I guess, built from source via rake task as manual says.

**Comment by bcardarella** [comment]
can you try the ember addon? Version `1.0.0-rc.1`

**Comment by meliborn** [comment]
Where I can find easy-form build after installing addon?

**Comment by bcardarella** [comment]
You don't need to find it, its an addon and so its is an npm module

**Comment by meliborn** [comment]
I'm writing app in Rails, so it's better to get build (one minimized file) instead of all this source code.

**Comment by diogomafra** [comment]
The project was converted to be an ember addon, you can see the most recent source code on the `1-0-stable` branch.

The question is: how to use an ember addon without ember-cli?

I'm not sure there is a good way. You can try to use [ember-giftwrap](https://github.com/ef4/ember-giftwrap).

**Comment by meliborn** [comment]
I just need a latest build as a one file to include in my external project :) So hard to get simple thing.

**Comment by diogomafra** [comment]
Yes, it is very hard. :cry: 

And I think going forward it's going to get harder and harder to use ember without ember-cli.

**Comment by bcardarella** [comment]
Closing in favor of #229
