### ISSUE TITLE
Deprecation message on didInsertElement hook

### ISSUE THREAD

**Issue by musaffa** [dockyard/ember-easy-form#218]
For the pages containing easy form
```haml
= form-for resource
  = input-for 'title' class='form-control'
  = input-for 'body' class='form-control'
  = submit as='button' class='btn btn-primary'
```
this deprecation message shows up in the console:

DEPRECATION: A property of \<project-name@view:-outlet::ember523\> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation. [deprecation id: ember-views.dispatching-modify-property]

I' using ember-cli 1.13.13, ember 2.0 and ember-easy-form 1.0.0-rc1

**Comment by diogomafra** [comment]
Can you try the branch `1-0-stable`? This PR was merged a few days ago: https://github.com/dockyard/ember-easy-form/pull/217

**Comment by musaffa** [comment]
Yes it is fixed in the `1-0-stable` branch. Thanx.
