### ISSUE TITLE
Cannot read property 'Config' of undefined

### ISSUE THREAD

**Issue by RodrigoBalest** [DockYard/ember-easy-form#221]
Hi.

I'm having this error. It's been issued by the line `Ember.EasyForm.Config.registerWrapper` on an initializer.

Also, I followed the [wiki about Bootstrap 3 use](https://github.com/dockyard/ember-easy-form/wiki/Bootstrap-3-and-Ember-Data-With-Server-Side-Validations) and got "_Cannot read property 'Input' of undefined_" error.

I'm using the following versions:
Ember: 2.2.0
Ember Data: 2.2.1
jQuery: 1.11.3

Thanks!

**Comment by bcardarella** [comment]
Closing in favor of #229
