### ISSUE TITLE
'ember install' installs 0.0.0 package version

### ISSUE THREAD

**Issue by gandalfar** [DockYard/ember-easy-form#222]
When I do:

`ember install ember-easy-form`

I get `"ember-easy-form": "0.0.0"` in my `package.json`, that is just an empty skeleton of a package. Manually updating it to `"ember-easy-form": "1.0.0-rc.1"`, and running `npm install` fixes it.

Not sure what the fix is, but this is probably not expected behaviour.

`ember -v`:

version: 2.3.0-beta.1
node: 5.0.0
npm: 2.14.10
os: darwin x64

**Comment by bcardarella** [comment]
Closing in favor of #229
