### ISSUE TITLE
More flexible input html

### ISSUE THREAD

**Issue by musaffa** [DockYard/ember-easy-form#223]
Currently `ember-easy-form` allows only class attributes to be passed to the input html tag. Rails' form builder [Simple Form](https://github.com/plataformatec/simple_form#usage) has a feature of `input_html` which allows `class`, `id`, `data` attributes etc for the input tag. Those input_html options are also passed to `Simple form`'s custom input which can be used to configure the custom input types. Especially, `data` attributes of the input tag are quite handy in passing configuration options to the custom input types. Dynamically configurable custom input types open a lot of new avenues for a myriad of use cases.

We need a more flexible input tag options in `ember-easy-form`. The same also applies to the label, error and other tags.

**Comment by bcardarella** [comment]
Closing in favor of #229
