### ISSUE TITLE
Uncheck doesn't work on checkbox

### ISSUE THREAD

**Issue by musaffa** [DockYard/ember-easy-form#224]
On `1.0 stable` branch, checking a boolean attribute with a checkbox works but uncheck doesn't work.

**Comment by andrewfan** [comment]
@musaffa did you have chance for figure out this issue?

**Comment by musaffa** [comment]
Yes. I had to implement my own [custom input](https://github.com/DockYard/ember-easy-form/tree/1-0-stable#custom-input-types). 

```Emblem
= input-field 'published' as='checkbox'
```

```Javascript
// in the easy-form config initializer register custom input component
config.registerInputType('checkbox', 'checkbox-input');


// chekbox-input component

// template.em
= input type='checkbox' name=property id=property checked=isChecked
label for=property = labelText

// component.js
import Ember from 'ember';
import WrapperMixin from 'ember-easy-form/wrapper-mixin';

export default Ember.Component.extend(WrapperMixin, {
  classNames: ['checkbox'],

  labelText: Ember.computed('property', function() {
    return this.get('property').capitalize();
  }),

  init() {
    this._super(...arguments);
    const dependentKey = 'formForModel.' + this.get('property');
    Ember.Binding.from(dependentKey).to('isChecked').connect(this);
  }
});
```

**Comment by andrewfan** [comment]
if you will render `input type="checkbox"` inside custom component's template logic with setting `for` attr for label (https://github.com/DockYard/ember-easy-form/blob/1-0-stable/addon/components/internal-input-for.js#L84) will break, so instead of creating `input type="checkbox"` inside custom component i extended custom component from `Ember.checkbox`
something like this
```
import Ember from 'ember';
import WrapperMixin from 'ember-easy-form/wrapper-mixin';

const {
  Checkbox,
  get,
  Binding
  } = Ember;

export default Checkbox.extend(WrapperMixin, {
  classNames: ['ember-easy-form-checkbox'],

  init() {
    this._super(...arguments);
    const dependentKey = 'formForModel.' + get(this, 'property');
    Binding.from(dependentKey).to('checked').connect(this);
  }
});
```

**Comment by musaffa** [comment]
If I click on the label rather the check box my custom input component still works. So `for` attribute should work. In any case, if your own implementation works for you, that's great.

**Comment by bcardarella** [comment]
Closing in favor of #229
