### ISSUE TITLE
make `knownProperties` for `input-for` componen public and editable

### ISSUE THREAD

**Issue by andrewfan** [DockYard/ember-easy-form#226]
Hello, I faced a situation when in previous version of ember-easy-form it was possible to set class for `input-for` component itself by passing `class` in template, now (`1-0-stable` branch) `class` key is skipped on the step when setting keys for `input-for` component and my passed `class` applies on `input-field`.
For now i fixed it in initializer 

```
import { knownProperties } from 'ember-easy-form/components/internal-input-for';
knownProperties.addObject('class');
```

maybe `knownProperties` for `input-for` component should be in `config` object and be configurable?

**Comment by bcardarella** [comment]
Closing in favor of #229
