### ISSUE TITLE
http://builds.dockyard.com/ 404

### ISSUE THREAD

**Issue by yingliangzhang** [DockYard/ember-easy-form#227]
Hi,

My project is using bower to install easyForm:

`"ember-easyForm": "http://builds.dockyard.com.s3.amazonaws.com/ember-easyForm/canary/ember-easyForm.js"
`

But looks it has been removed?
![snip20160824_25](https://cloud.githubusercontent.com/assets/3793091/17917900/a2e774ba-6a03-11e6-8427-94c99ad60459.png)

**Comment by bcardarella** [comment]
What version?

**Comment by yingliangzhang** [comment]
Not sure about the version. The url that is 404 is in the README. Looks like the s3 bucket has been removed.

![snip20160824_26](https://cloud.githubusercontent.com/assets/3793091/17924138/bf5cc5a6-6a2a-11e6-917c-f17ae740c506.png)

I managed to install it using `npm`. But you probably need to the README.

**Comment by bcardarella** [comment]
Closing in favor of #229
