### ISSUE TITLE
Error messages don't show on form submit

### ISSUE THREAD

**Issue by flynfish** [DockYard/ember-easy-form#50]
**Note: I am not using ember-validations**

Steps:
- I have a form
- submit the form
- error comes back from api in proper format: 
  - `"{"errors":{"email":["can't be blank"],"password":["can't be blank"]}}"`
- set the errors object on the controller in the model.save error callback
  - `_this.set("errors", error.responseJSON.errors);`
- Errors are not shown (but they are if I then focus on an input and then focusOut of it)

This worked in ember-easyForm#0.3.2 but doesn't in latest beta. 

Looks like d34589327dc7da82527051f9b635e1131fd7b8e0 is the cause

**Comment by bcardarella** [comment]
Closing in favor of #229
