### ISSUE TITLE
browser login recognition

### ISSUE THREAD

**Issue by ferluszt** [dockyard/ember-easy-form#59]
my form is:
```
<div id="login-top"></div>
<div id="login">
	<div id="login-wrapper">
		<div id="login-banner"><h3>LOGIN</h3></div>
		<div id="login-content">
		{{error}}
		{{#form-for this wrapper="form-vertical"}}
			{{input email label="Email Adresse" }}
			{{input password label="Passwort"}}
			<input {{action signIn}} class="btn btn-large btn-success" type="submit" value="Login">	
		{{/form-for}}
		</div>
		<div id="login-bottom">
		</div>
	</div>
</div>
```
i have the problem that no browser (firefox,chrome,ie) is recognizing my password

**Comment by diogomafra** [comment]
This is a limitation of the browser, I don't think we can do anything to prevent this issue.

Check what the Discourse project is doing [here](https://github.com/discourse/discourse/blob/73336db311c3889c1ad28059e5b7fb5f186e5b4d/app/views/layouts/application.html.erb#L73), [here](https://github.com/discourse/discourse/blob/0f7aaf5ab19f593416a0012f223e2f91e6cb0329/app/assets/javascripts/discourse/views/login.js.es6#L18) and [here](https://github.com/discourse/discourse/blob/ad98f270c925e7cbdfdf7d7687605b49656503b6/app/assets/javascripts/discourse/controllers/login.js.es6#L78). They are using a form directly in the static html.
