### ISSUE TITLE
Reset fields' focusedOut states

### ISSUE THREAD

**Issue by cvincent** [DockYard/ember-easy-form#72]
What would be the best way to go about resetting a form's inputs' focusedOut states? I have a page with a form which uses ember-easyForm and ember-validations. Once it is submitted successfully, the model's fields are cleared so the form can be reused easily. Unfortunately, this causes the form's validation errors to appear because the fields validate on presence. Is there an easy way to "reset" an easyForm from the controller?

I wasn't sure which project to submit this issue to, but it looks like the focusOut stuff happens on ember-easyForm, so it seemed most appropriate.

**Comment by bcardarella** [comment]
Closing in favor of #229
