### ISSUE TITLE
Force showing errors for the form

### ISSUE THREAD

**Issue by lowski** [DockYard/ember-easy-form#90]
Hello,
I have server validation enabled for the model (I'm using Rails) and I would like show the error messages from the server I've set errors property in the Controller how to refresh the form to show this error to user? 

Right know I have something like this (but even though I change errors property, they are not getting re-rendered):
https://gist.github.com/lowski/8122693

PS. I'm using ember-easyForm 1.0.0.beta1 (Last commit: 289fd57 (2013-09-14 18:00:30 -0400))

**Comment by bcardarella** [comment]
Closing in favor of #229
